### ISSUE TITLE
Installer doesnt work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Wlanfr3ak** [mriza/winbox-installer#9] opened 2018-09-10 06:49 UTC
user@hostname:~$ cd /tmp
user@hostname:/tmp$ git clone https://github.com/mriza/winbox-installer.git
Klone nach 'winbox-installer' ...
remote: Counting objects: 80, done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 80 (delta 13), reused 8 (delta 3), pack-reused 55
Entpacke Objekte: 100% (80/80), Fertig.
user@hostname:/tmp$ cd winbox-installer/
user@hostname:/tmp/winbox-installer$ sudo ./winbox-setup install
./winbox-setup: 137: ./winbox-setup: [[: not found
./winbox-setup: 53: ./winbox-setup: [[: not found
Downloading Winbox..../winbox-setup: 60: ./winbox-setup: cannot open 60: No such file
./winbox-setup: 60: ./winbox-setup: [[: not found
DONE
Copying files..../winbox-setup: 72: ./winbox-setup: [[: not found
FAILED
user@hostname:/tmp/winbox-installer$ ls
icons  License.md  LICENSE.md  README.md  winbox.exe  winbox-setup  winbox.sh

When i use it wit bash:

user@hostname:/tmp/winbox-installer$ sudo bash ./winbox-setup install
Using previously downloaded winbox.exe
Copying files...DONE
Creating application launcher...DONE

Please fix the Readme.md and at the bash

**Comment by phrxmd** [comment] 2019-01-02 14:04
#12 seems to be a duplicate of this.
#13 is a fix.

**Closed as completed** 2019-04-21 09:43 UTC
